controller_manager:
  ros__parameters:
    update_rate: 10
    use_sim_time: true

    differential_base_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    
    torso_controller:
      type: joint_trajectory_controller/JointTrajectoryController

differential_base_controller:
  ros__parameters:

    publish_rate: 10.0 # You can set this higher than the controller manager update rate, but it will be throttled

    use_sim_time: true

    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    twist_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

    wheel_separation_multiplier: 2.9
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    left_wheel_names: ['l_front_support_wheel_joint', 'l_back_support_wheel_joint']
    right_wheel_names: ['r_front_support_wheel_joint', 'r_back_support_wheel_joint']
    wheel_separation: 0.375
    wheel_radius: 0.06
    position_feedback: false
    open_loop: true
    enable_odom_tf: true
    use_stamped_vel: false
    wheels_per_side: 1

arm_controller:
  ros__parameters:   

    use_sim_time: true

    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - upperarm_roll_joint
      - elbow_flex_joint
      - forearm_roll_joint
      - wrist_flex_joint
      - wrist_roll_joint

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

torso_controller:
  ros__parameters:

    use_sim_time: true

    joints:
      - torso_lift_joint

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity