controller_manager:
  ros__parameters:
    update_rate: 10

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    arm_with_torso_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

arm_with_torso_controller:
  ros__parameters:
    joints:
      - torso_lift_joint
      - shoulder_pan_joint
      - shoulder_lift_joint
      - upperarm_roll_joint
      - elbow_flex_joint
      - forearm_roll_joint
      - wrist_flex_joint
      - wrist_roll_joint

    allow_partial_joints_goal: true

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

gripper_controller:
  ros__parameters:
    joints:
      - l_gripper_finger_joint
      - r_gripper_finger_joint

    allow_partial_joints_goal: true

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity