controller_manager:
  ros__parameters:
    arm_controller:
      type: position_controllers/JointTrajectoryController
    torso_controller:
      type: position_controllers/JointTrajectoryController
arm_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - upperarm_roll_joint
      - elbow_flex_joint
      - forearm_roll_joint
      - wrist_flex_joint
      - wrist_roll_joint
    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
      shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
      upperarm_roll_joint: {trajectory: 0.1, goal: 0.1}
      elbow_flex_joint: {trajectory: 0.1, goal: 0.1}
      forearm_roll_joint: {trajectory: 0.1, goal: 0.1}
      wrist_flex_joint: {trajectory: 0.1, goal: 0.1}
      wrist_roll_joint: {trajectory: 0.1, goal: 0.1}
    stop_trajectory_duration: 0.5
    state_publish_rate:  10
    action_monitor_rate: 10
torso_controller:
  joints:
    - torso_lift_joint